env:
  global:
    - secure: rT+RZxo8WNgyK4MILGP+ANdmiB+q3k3aRijsmPgivt4l7o2lQAx+nRulHHk2KGJHQ2fTtrZUPvPYws+PoPLgRMaJ3ReiF6WNB7SkOb74Qs/YyXaSxO4+q2WHMgMGWMKEUdAHmI3JfaR2CEoPPmw2TYW46KxffNMYie6eaZym+xW+8/vJXxIvf4OuHLKlcTUcdG20sFG3jT7IklQUG2qaUe3oQx/T4f6RRy2+Ug64a/ZHxKw7aLFSU1/cwQiMOUdBLLIOERkuTEPwS5VKdeNc8XmtUIG+Tq320Px5L7R8HWdYZd3GtEIPPyyIE8l9+kVfveWd4g1jHt2TI8ura8woWe1+eQVXRMWJs1unEMV+t1BBqdijh8aeyRKGLV0DmSIhwJZd0Kz/Y/SXu75GHpn0/xfR1CcnhQyw2xHCvDoxnd8lUb/Y+PbAw+d/ysdK5fF23iE1NYF5abyKXIDGwCMHzcsg8uqjGU7eOA1fP+dlujYpsBbmiIpi5jMqffisqxZfwauzrBkq+wXZwotUhsITtvIcmVy6597vg5thlaOFPmRHHWCQAs2T0KODvzT+LQKYmzkSUkjttFwuGUUMEpOLYMtkmpwGGLTtd6AFgIP4K5h78+k+chom+yM6+0h1aFplrAqbHRow/5uVQWlMPYl+txjIHoT0E/6be+NhvEhaNaI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
