env:
  global:
    - secure: TMBPmc48xcY1PqR7Ma28gyJSjzXOl+ubuCl/hFyt3upPT9RH+fkGgvdB6t4lH5OGftqup5uRlC1HgfC/f4FOvZ/W7fEZXtxDtbdQgR/YKAeCoW9YBtZLOY0fWYuAHuCW5Mz3ADKJZzx0Pj6BWQUQPwRS6umOFDsvgQ46w0f7kktXkJhWKDD2H4mI9us34HcA7m5fm/Q12lPk99NnbGNeXGSgswb7ftM0DN5PNzlEdc7UlyHjEe+sZPIGL8P/qT1h1RiXPFOkIdMFZBRFyyF9QvSvJAR36GGWvN9hIv5T9AfkHl7LuDaOH/kMoVuJhN3TGgCQ85BlUsgu6JnMkeVcIRA7W/MaTC/3/cKdvYB6WU2/qk+oZhW+pIRCbLVKnZ7T3AwMVuMLI2uMLvH/5avLjoNB1f0FSqncjvQrMYB3InZUQliP6t5fB8awdqPVcfQQuJ2lniaM3nGb46kt6MHOcYPBPhCcQsOa3HPpeJAvU4HnIut92pGu7aGf/6Vhrhh71aGocNtzZ+do9tD14JFROpNGwnckaDtRR8VteGXHikBxlMDkXSJUeKlm1jZMBrpqXeMekPa0COjIqQdvQo/TVcOYnEFlV+DG88qaF/A/DYDtawurAULgnUSWWwUUOeVs0Swx/7s1v1w14ucL7dYF2MOkqzzvrSbhyzwL5hbHe2Y=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
