env:
  global:
    - secure: b4S6Ym2q5kWjqd8i1PcN4NX49u5w8XgdVDtuklXOcE0wxcLMFB56PtNFk7UQbQxM/E6bWlOdzmZt0KqqH5GBIcxs2qPQsfkpAg7Bduyn4hG/QnFnAQiTLRToODUyXbJg0Ti8/QY9UfwqioUk39DJnKSbXrbZI2+HDmFUdag1A1DSZ3jiH/sZmi6tu71CTY5xFnFnzqN+qPTEherB6P3GpprIDG5F7qxd8kosnyB0IaW1UvIkEC4BVhBCmvuHhDFP11Rso8LaPLy/Mzl+g/kM+B8yIO7ZD5Tr4wzPvuAq0Rsz6wUlVyCQtkq/AqZZCUMn652pu1ysOOU13ondeBybtkvoUsHsqM9LKwSAvRED6lPOJfTRiD94BEfuJ2dU5Fli6VfzIkHy560pFWUoFN6R7+mUvkR3zP1D9xrjX0H9ocPmArXsTbbz8MOViNNHDB/QBIS+vElU7cVzm9SW+e97u4BKf+nNJe68IyoInzcVktxxKpQV7ArvMptiwm08U97D4cOYojv91CDEbenhsi8Fl8SAZLbgZTt0eiu3A3F83KOu1wiF76HUhtfsTQj5l5IVQz10ooPaGdC9C1952ZRbv+U8uvBfZuFsJRmL1c1Z6l/JvAUpBJky+PYjAu13FO6CWwR7tth2yhzBqnjkGveCErNnfIS/q1Xo/G8kfZ/CZeM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
