env:
  global:
    - secure: zfOU5g2MMN5Rk+PkIUopMvJYiwCn6JUlEI18b2p9sAj5fKmoSict4CduaD6X7z3Zs0z6JEplUMr55+av7P5Adxq8Qp7YWumzYJG77lM9lr5l4OYdOdYa8TNf7HZLcyYYJvIobAj3aneJkKAU9w6VkTTFTmNLVvkqpWMLV07SE1mOOrZP9TeDV9C8FUAqwYIB5lVW6EH0EYxA2kqcqCGTTT8MprrbycgP5peE/gJWjaoA4At8WDYWz/97aJuvvG5ec/MIviXZf31JXqQxAstZ0y5Lk/Z23E7tLP5RYwH7BQ2XHict+yosBcUEJv9gAbabVvO/oScx8pyK2/KFQ8B9swDVkahQoUeI0HyqjVRORja6DoVCjFyRHUi7lISNeCWuFJYB0UBQESBRM2ppv1T/mmnq+pZTMq6+k3QFsT8+TCgQccxdfKMQr3iqg3MiXKUyQaTmNOlglucoA/ldBEhOz2zAmpePga1xeac97Cxh5wzHzejp9xJmf8rQrKW24QAUwGGUzrejaoyFdkr+o3yW6vEmoYzz5wwh8iKuXH36o3O6kzJGKCYv2zCHQS+NZE+crtuMdJgyL6RnrkOoWWguempDr2eUynoAEs4qXbtT9W3AlnmQJLh/PmUQsNWc8p5KgC3ZPm1IP0PM9y3TM8rAoneewadRZVjzFiuYscprm18=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
