env:
  global:
    - secure: tPVwjm26XmEIplQK1xmsyUJTj8erhS15A34AKoD+fDaykcnPZ+0Vdutx5RoJQnKdXigVoJc7LIfbLLYHfXf0IKjlgk/7i3TffIf7ZpAcuHUD0BcAUtlMOE6JtmjwZRtgvcCFMVsUcmWnmFCnQvIA3ADu00/adMgeZ0YyNun3DG+BDstVsLcTxytnnMwZVVStxSo3ZPeomtn/A7wXKzn29OY0AambL5XXdw7Kl++2TOxmyrDy7LJ35ZqQf4alyFcKWnvjcfFEACZtHXHSMHLotEJyeRtvX0kjRBmwOiloDZWo+sshf+CdEkE59d/X1o3aWa2w1l/zZYHEX0xFY4x2BNBJ453BXgjmFUW9/Qeog4t+B+ZeG+0TH961ZWAYo7qC/DxJJrSvjT59HYsy+aphb47F0J8co2Z9JcEyYCo7Vj1pTXH3VcNmg6MzI/mtUNFdymI+Vy2ZXWVFyb6uSrqX4EJaO6KfYsBBRcGyBftasmSKuY4QUFpRKsG9Y04l5J+tJkwMvcMniiCygouDb17zwXBs72h2EiH6akeO0rtV5qCniGq+hWPtF26GsQsUO1at0rUpPbA8fS/84koJgoCppELPo1/3o3s1jD4rvA3gIct6gC0/v3ehsqu7hWyAg+4y6lvw7DjmHfAT0JdysGaz8PoTZGNCuL7tMyaeg+e0eaQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
