env:
  global:
    - secure: uAyEQlBCZdK1u9HVilDYKDu89m7fLYXnsMFlCPvliNaLtPuzAF7X+35OeNx2w7L3sw2StcLdP5IQs022E+rLk+Cm335DpsyoPuPNkj4ZhRYZ92n6BOYjAFnXIjb3ighIC9dXvxQg9PNrR6KOo/kUkNi4e8ObbHF/XHYzvYsxfs9NVtQsG15PzwXIT14bNFXP75DvSIso24QqurWbXHc3UyO03zU+d9jgWTXc5oV3psHpJm9qKCNaECQSHhJ1mp5pD77aPDTnfJ+01x1+cR2Saj76sd+h0D/gGpRPSXwFNiVe78UQH78PdBkGJv/w+U+Ewds3+pOHQjyuabcgK8bvIcYAp4eu9qtiKmM3wAA8LgWYDWafn352VJO14XYNX3lL423m/7bM/p76rCzitxVFDFCVcDsmtoTvRh0o7siH2R12ov5JAr2/NeXsDWPvKM7+FwRCdPyz3dfB4xBR2LhAORkbbEmx4m+PN8vHkVVlH30Ee50bOdnpdIDy9+Ltv+YrYL/CsEzGZzMewHmx80mqcBwMiQVI8nZnW//oCS6e+YD0SyHlaybI3lRJVdxHpZqG4NOI06t1cvetqKQ/uaH0Ju1zVJ+GzjguAdF46WbG1j1XJzFNsFnTLtJYR0faR/iPx8F/n1Ff1DN2UfKefDHi9BBGKUpcTF6sMG9F6ZL/zKk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
