env:
  global:
    - secure: pFronJ7yoQNp7eBS0hvsjnTQDvJzybYiXWu0XX8ghJN/1io/mT82W5k7QN5PNzTn+ocCtTMPy7sLTKC4Jpe/OzZt6EEf2SwDtQjishOA4mh34/PrB1bbnhbA/DUPLoEInc+8K+3Nr1GXH3UuJtHS9oHu47KrlBUCpn5WEqfcTZuPFhBwj2E8Yo3oBtjEr09oa9sFz3+NbijVWQLt6fD0QsfmR1Z1VuvAADa8rcwvgAu5waJ3a3gVU/vAUM63peQAloX16CfeSrok4WjlDnG9fOYxm5W6O/XTwhYmeUxK4w9MtgzHQwfMB7hNcd7CZkmDYevp4art0hsnyNo+JsLv8HSRrGNxkGaW12I+EoP7kcL08S3zofQpiijUJ3hmk7DZWbk6p5rXqd2JtAOJcmbE7o0cEVSE2hjPixM34HZmubnJo5vOAzU/7XiyCE5A0JQVeoHEkxWP0VrO+UynLUMVnNFgksbqkFke5fa/waRaPEni8mewJgGyij+UpqIAwqde4g3dGIuubZyqZzL280/xrFGMCf+egbVd9PIXw3j0zTT66L5i7HZntNJ6Nez99nDa+npice+uqMjLnM+sKJiL5ubXQHgOvhtGnRKdCqspEwHbukPNN4K+w2NM6uf5VQT3vqCNhQCTHswttN34AATFsl4WairMhQmkGABdN4+otSA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
