env:
  global:
    - secure: J/WSPnfeykW0LIHnCa0aH/pTXUSFDWpr0zlv/KKVSWlA0XLgn7zTBBmi5hDWC23LIUhXIQA/mJ/xbxWywOErR/25/rrge5fg91Qp0s1frsL7LU0R3/Ybtj2YqWTUBvm/5AHLbcNzlFNJmSXvJ2pWeRif3RwCUJWDf85/iDqyl2K1snNtNm3dMPUkzhUCN7PoYPpsQO13oxPbd9HLSoEi9YigOahoCYupjh0TPMTtxJRaARccPRCm9vLq/S5fkjtluKNELjXJg+qSTbKznPEngwcSBJi2vHcMEexT0HLeVWr2gRVqM4Oh/BoCAQPsk4VNA/Qknl8WQgajjxwa+AnDa/41j5gQ9lXi9tThYmvbCpiNQ7pQia35XOiDlygvHNujxJdTFhnfqEtFfXyaZ4twTUaSalvUQPJV0WezF5Wu02oARNaC3ZKBQoVwQjymxI6kahV4P9PYsdq/WZGPXLnAFWrqvFfi49EeJCXPbP2bDLrGC18hBkNNIu+2rbVXKAQQ4ttHsTmZBG0jpxoOW/3x7vdLqYZggJmVYpNyukpRCPXne85wnQwOW0kjRFSxLY5TsVYjHJ7xeOeV9T1zMz9CVxbuvEU2CdC5eUVV8shWzdpV9Q1tajbhXBr4VDSBBwZ07zJDzYM7RtWg3e70HGJydBfZYyoj6iq+1sJZsUo5Ha8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
