env:
  global:
    - secure: iEEqxWAHCYTnHYW1S/xCVquaOXKHWLtXBJ/cIf9LlYb5+LP1M+XzYkqC24m7aHN1Vl819+oZPKfU8sp2jpFWLK8d8GQ+01quz5Vv9U9VNp6cXSzu45oO+JDSACSTrNhO9X9v+OBziqohfjFuLCW4pOCEKm1LlEDyGSz8idUv5WOTezJhtHukdz7S6y4iUFoHvmIKUlyW3AvFFSz/0aTZE+ltowElM0krvvSolIoWxobxDGMGGSzN0jRspIKGWGRsVrzVmx/a3oI/WuCUsmlybpW5W2nOnTubdLktCxBd3yLhYSVlkFNiygjJD9ztbBWNiPQn3vd8f7rMP5FEKIO8WtZWxTC1jWQZrx1Jir1hc+x7tei1vuUxSIPWWVLOR4i6aznpkqe7RG55Y+qsN4NMjKNj+ZyeFPTF5H3SxG9EL4WqSC/21HwwqShlrlFZ82u971k1oJErBW4F2s6QZLW706+KbgpxzHkthlg4FBFZGZVlh0HMhGejooaAEJp5SRmmm5A63T7JYcse6qPuyvvos+JrjNM3t3RH4Cq4/nQ/uCsgu1d+hn7tGcopZPXZlvmN35zIWKKO1aPAolv5KmdAFwaVA9yS1SIDwFdgKK0jKWIXxq4khy7KUDLiwwPhsiz7pQ7Q8/Bs7J1dPDJ98Rgks2Ln31UujWfZj38jffsn59Q=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
