env:
  global:
    - secure: fwwvXk2k9A4WtylZZrTaV8nDV+XwlW+8P0c+zSBteIX7He2q+2ofwYlBW4UQdtHhVsqxupfI0wjJt0r5TPrkYVol2bfCPQ5zd6sSNMB3wkfoGh4VrEUDZc3ypga5nbZByXqwdpdY3AEwzwRA3ouTGFizZHGiWWusVPxZp5w9QfPDYvjwwgTXs1A/1jEUaFphIgsXXXyTuQouhiLioYHVZRx2cVoOBrOe5jRJNcjBus+gDdL2Cm/xcP3VRIayJGSYGzZBO0ZZllgZzlWO0KC8MTqhACMuR7zvMsy0EOacX6hsRblWoK8NU6Hyn4uSQ/qb4la04GvhM60nebQWFRGpFV80BJ8EEO+6GExBdad2+749ALxw4r+QTMQUKVhxdr5pYe1MWXSN1BWRkCGbZCALOTK3ceoQYc7EhSlHpLaYwoFmFaVwPK48EndwT264jsnz2lkRD1psf7diGk+geBXpInC7TcFwoAskn4CgurH7s+LFehAH7QtEmpM0+1lOfZvTyoauYgtbXRXXJrkSnHQeOBgXqwAWvjecDsPILScqIN8rh3/5doqb7CZg40JZbZIs2pgRAqSIppSllq0aKMnLhUK9716kHG9OrCLHhYu62qdiue/RVq2Rld2Ldi/dFVDqr6Ac1moP2sf5YHgVuGfkyjadGpHqyiAq5KHN8YsJR2Q=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
