env:
  global:
    - secure: GVnCXqHs/afeRW40SpyiNE/qugnK+gY4pkP4Jv+9fdd0DCNiTfw2zbURVcYtTmkqjoNy2xs8jPU3bwTRXc43jMkAYdbip5lx5MFHOpyZ8DF8v1STU0UNgQiH71l+ZMKe58BkY8GqOe2BtC8nH0M2zqNHy6pPmj4ZApoFGlyEZKNjxyv7zIORnuqHyY4sDaSBCYW6vz/nYKR8dMYNzRp8u0t9byxxoe4o8CREDZ5/uGSSqkAqxqeoJKGgpNCMXi8oZH/AIUrAB7o0HfCxNf0fwNoQcrjAx6oVFBE4DmSPBRIwq0ElxB8j1Zt8Nchvu3dtoATvZr6TG3itLa3mDlfxgO2ODeBQD/4MlXedmrd/QI+B8c7GKuSdzKnJuY3hVt9smv0kfRbSSQPkjMHdkvugknA/+AExYNCxXOyJS8WB8LWjFOS1/+fUmiUEeLXeVae7OofZtgcGa4dv9FjjtxAzD+TWg2YqDOFIGxqiKbknWtzCvBCxT6FJ/GuVpHlkE8bP/5dEWPKx4dMY7kjeqpy55yASF3U6SmvEQazwOjmoaVGOdr9d7cIGvnQP0LwBgDwVGNsr2mzZTa9xhfOvc25RpKA+wcztjSOz3KBFXO5VLlD7cyL9Z/xwD/zaxeDMW9nAiOvDvLNwkoXvJtuRG9rFeyi/eRCXZu3KMgEtR9sNHmM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
