env:
  global:
    - secure: nYxXePW11g5Roa71UmsjXoqXto+Jz/0CDkJwlqfO4bMNoJb15vzOqGF9LtkIJJo/ynKEp+YTQqU5DH/lztmu7AsQIJOK+ZtxykJ1DClE7t8xiolAcix3vj4aTNcAQpPrFfo+Mj+HLMkTiVIuzEPk0pJZ15vhlebI2aFpKddwXnvsnezTAloPNHeLzj826Sz+x8AbxX1HBbLSpzXIlIE2p6WT5m5FZwAT0YigzURIVO1LBXSdbbDSL+YLB2qTP+y6istniu1MDPfGWXhRoHNTUgjrd1lzY0HWK1H211/bIQSp1DabfRGkvDsFdurWIv9bGAQfRveD4m6qxLR0Yh1JCf5v6o7gGTpLlqvyMqrcTYl41ts2t2j+V2M7Ihu0Gll8XLOtNg+JsF9DG/lk94HT+fVkbMNM6ZqkonvwRiFCkEswq5jUYaGU/elPZQGpsY0JAgSP78ZBjWPaM6NhvPgeFqcg9vz19kpvQrv9NNGW+yaFObDGLYIvw8IBm2rIXoYFtRmdKlnjX222057r8PONPNuxELo1L+/Qi144R+m7SN7ky9dcqywarMgHs1h4DeQpzSJObt0/9WeaPfh9U5sbBzdnZzMjdlBGlZxcTDgIYOi4GANsu9zLI9e45xlnb3NbphJA8hBvBnoR/PPW1Rx98XthCU08AOZk7miHRSSCtHk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/Ad-filter-list_web_disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
